import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 👇 ADD THIS
const leagueSpartan = localFont({
  src: [
    {
      path: "../public/fonts/LeagueSpartan-Black.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/LeagueSpartan-VariableFont_wght.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-league",
});

export const metadata: Metadata = {
  title: "FirmPay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable} 
          ${leagueSpartan.variable}
          antialiased overflow-x-hidden
        `}
      >
        {children}
      </body>
    </html>
  );
}
